### ISSUE TITLE
Divide by zero error [1.7.10]

### ISSUE THREAD

**Issue by Claycorp** [VelocityRa/ChameleonCreepersMod#3]
http://pastebin.com/P35t5vUT

Using RTG with BOP and climate control.

Also I recommend that you pick one issue tracker over the other one. Github or curseforge. I personally prefer the Github one over the curseforge one. Makes reporting issues and managing them easier.

**Comment by VelocityRa** [comment]
Thanks for reporting the issue! I've seen reports of "Creepers sometimes beeing invisible for a split-second" and it turns out it's the same issue.
It happens when they fall out of the air, without any blocks near them.
I have fixed the issue in update 1.4.1 in both 1.7.10 and 1.9.

**Comment by Claycorp** [comment]
Thank ya much!
